import bandana from './bandana.webp?url';
import cepk from './cepk.webp?url';
import digitalMobile from './digital-mobile.webp?url';
import nft_1 from './exclusive_1.webp?url';
import nft_2 from './exclusive_2.webp?url';
import nft_3 from './exclusive_3.webp?url';
import nft_4 from './image_3.webp?url';
import nftImage from './main-nft-screen.webp?url';
import nftMobile_1 from './nft-mobile_1.webp?url';
import nftMobile_2 from './nft-mobile_2.webp?url';
import nipseyBg from './nipsey.webp?url';
import unlockableVideo from './nipsey1.webp?url';
import pods from './Pods.webp?url';
import poweredRair from './poweredRair.webp?url';
import rairTechMobile from './rair_tech_mobile.webp?url';
import videoPresent from './video-present.webp?url';

export const NipseyBg = nipseyBg;
export const Nft_1 = nft_1;
export const Nft_2 = nft_2;
export const Nft_3 = nft_3;
export const Nft_4 = nft_4;
export const NftImage = nftImage;
export const UnlockableVideo = unlockableVideo;
export const DigitalMobile = digitalMobile;
export const NftMobile_1 = nftMobile_1;
export const NftMobile_2 = nftMobile_2;
export const VideoPresent = videoPresent;
export const RairTechMobile = rairTechMobile;
export const Bandana = bandana;
export const Pods = pods;
export const Cepk = cepk;
export const PoweredRair = poweredRair;
