import greymanRose from './greyman.webp?url';
import greyMan from './greyman1.webp?url';
import greyManNotFun from './not-fun.webp?url';
import flyinggreyman from './pic1.webp?url';
import greymanVariants from './pic2.webp?url';
import greymanMonument from './pic3.webp?url';
import greymanArmy from './pic5.webp?url';
import greymanMatrix from './pic6.webp?url';
import greyManTimes from './pic7.webp?url';
import PlayImages from './playImg.webp?url';
import PlayImagesColored from './playImgColored.webp?url';

export const GreyMan = greyMan;
export const playImages = PlayImages;
export const playImagesColored = PlayImagesColored;
export const GreyManNotFun = greyManNotFun;
export const GreymanRose = greymanRose;
export const Flyinggreyman = flyinggreyman;
export const GreymanVariants = greymanVariants;
export const GreymanMonument = greymanMonument;
export const GreymanArmy = greymanArmy;
export const GreymanMatrix = greymanMatrix;
export const GreyManTimes = greyManTimes;
