import aboutPagebg1 from './aboutPage_bg-1.webp?url';
import carstonImage from './carston-hs.webp?url';
import davidImage from './David.webp?url';
import edImage from './Ed.webp?url';
import garrettImage from './GARRETT.webp?url';
import guntherImage from './Gunther.webp?url';
import juliaImage from './JULIA.webp?url';
import martinImage from './Martin.webp?url';
import matthewImage from './Matthew.webp?url';
import michaelImage from './MICHAEL.webp?url';
import rairProd from './rair-prod.webp?url';
import sethImage from './Seth.webp?url';

export const aboutPageBackground = aboutPagebg1;
export const David = davidImage;
export const Ed = edImage;
export const Garrett = garrettImage;
export const Martin = martinImage;
export const Julia = juliaImage;
export const Gunther = guntherImage;
export const Matthew = matthewImage;
export const Michael = michaelImage;
export const Seth = sethImage;
export const RairProd = rairProd;
export const Carston = carstonImage;
